The H2+/H3 are supposed to be able to encode 720P 30FPS. Could we study the existing super cheap HDMI-to-USB dongles so that we can replicate the circuit for the hat?
I'm not so sure it can handle sound, but we could then do the same thing for the super cheap USB sound cards...
